{{- if or .Values.config.auth.tokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nklave.secretName" . }}
  labels:
    {{- include "nklave.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.auth.tokens }}
  api-tokens: {{ join "," .Values.config.auth.tokens | b64enc | quote }}
  {{- end }}
{{- end }}
